name: Production
on:
  push:
    tags:
       - 'v*'
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerlease: false
          generate_release_notes: false

  build_release:
    name: Build Release
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: windows-latest
            release_suffix: windows.exe
    runs-on: ${{ matrix.os }} 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.0'
          architecture: 'x64'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Run Linux
        if: matrix.os == 'ubuntu-latest'
        run: pyinstaller main.py

      - name: Run Windows
        if: matrix.os == 'windows-latest'
        run: pyinstaller main.py

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: release_${{ matrix.release_suffix }}
