# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: setup python deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.13'
          architecture: 'x64'
          cache: 'pip'
          
      - name: build exec
        uses: Nuitka/Nuitka-Action@v0.4
        with:
          script-name: main.py
          onefile: false
          
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: build/

      - name: upload release artifacts
        uses: actions/upload-release-asset@v1
        with:
          upload_url: $${{ steps.create_release.outputs.upload_url }}
          asset_path: build/
          asset_name: typingTest.linux-amd64.zip

